use anyhow::{Result, ensure};
use clap::{Parser, Subcommand, ValueEnum};
use std::{collections::HashSet, fs, io::Write, path::PathBuf, process::Stdio};
use xtask::{bench, prefill, report, util};

// Compile exactly the same fragments as the engine; no source-text parser.
#[path = "../../src/kernels.rs"]
mod kernels;

#[derive(Parser)]
#[command(about = "Cherenkov repository tasks")]
struct Cli {
    #[command(subcommand)]
    command: Task,
}

#[derive(Subcommand)]
enum Task {
    /// Run the complete-answer benchmark suite and pelican gallery.
    Bench(bench::Options),
    /// Compare prefill throughput between two executables.
    Prefill(prefill::Options),
    /// Regenerate a saved report without loading a model.
    Summarize { directory: PathBuf },
    /// Rebuild the README benchmark section from a completed saved run.
    Readme { directory: PathBuf },
    /// Build the mdBook guide and workspace Rust API reference.
    Docs,
    /// Syntax-check all assembled Metal libraries.
    CheckMetal,
    /// Check that a GitHub login is listed in AUTHORS.
    CheckAuthor { login: String },
    /// Write kernels/.clangd so clangd sees each fragment as the assembler does.
    Clangd,
    /// Run explicit live smoke tests (starts its own server).
    Smoke {
        #[arg(value_enum,default_value_t=Smoke::All)]
        kind: Smoke,
        #[arg(long)]
        model: Option<PathBuf>,
        #[arg(long)]
        binary: Option<PathBuf>,
    },
}

#[derive(Clone, Copy, ValueEnum)]
enum Smoke {
    All,
    Server,
    Control,
    Sessions,
    Download,
}

const LIBRARIES: [(&str, &str); 3] = [
    ("FORWARD_MSL", kernels::FORWARD_MSL),
    ("BATCH_MSL", kernels::BATCH_MSL),
    ("CLOCK_PROBE_MSL", kernels::CLOCK_PROBE_MSL),
];

const CLANGD_PATH: &str = "kernels/.clangd";

const CLANGD_HEADER: &str = "\
# Generated by `cargo xtask clangd`; do not edit by hand.
#
# clangd (through the metal-lsp extension) parses each fragment on its own,
# but src/kernels.rs assembles the fragments into whole translation units.
# These flags reproduce that view: the prelude supplies the stdlib include
# the assembler prepends, and each fragment includes the fragments before it
# in its library. Paths are relative to the fragment's directory, and every
# fragment lives one level below this file.
If:
  PathMatch: .*\\.metal
CompileFlags:
  # Keep relative includes anchored to the fragment's directory.
  CompilationDatabase: None
  Add:
    - -I..
    - -include
    - clangd_prelude.h
    # Suppressed errors still count toward clang's default limit of 19.
    - -ferror-limit=0
Diagnostics:
  Suppress:
    # MSL puts [[host_name]] and [[kernel]] on explicit instantiations.
    - attributes_not_allowed
    # metal-lsp maps `device` to `volatile`, which C++ cannot copy from.
    - ovl_no_viable_oper
";

/// Fragment paths in assembly order, read back from the `#line` directives.
fn fragments(source: &str) -> Vec<&str> {
    source
        .lines()
        .filter_map(|line| line.strip_prefix("#line 1 \""))
        .filter_map(|rest| rest.strip_suffix('"'))
        .collect()
}

/// Editor-only clangd configuration mirroring the assembled libraries.
fn clangd_config() -> String {
    let mut config = String::from(CLANGD_HEADER);

    for (_, source) in LIBRARIES {
        let fragments = fragments(source);

        for (index, fragment) in fragments.iter().enumerate().skip(1) {
            config.push_str("---\nIf:\n  PathMatch: ");
            config.push_str(&fragment.replace('.', "\\."));
            config.push_str("\nCompileFlags:\n  Add:\n");

            for earlier in &fragments[..index] {
                config.push_str("    - -include\n    - ");
                config.push_str(earlier);
                config.push('\n');
            }
        }
    }

    config
}

fn write_clangd() -> Result<()> {
    fs::write(util::root().join(CLANGD_PATH), clangd_config())?;

    println!("wrote {CLANGD_PATH}");

    Ok(())
}

fn check_metal() -> Result<()> {
    let mut failed = false;

    for (name, source) in LIBRARIES {
        let mut input = tempfile::NamedTempFile::new()?;

        input.write_all(source.as_bytes())?;

        let child = util::command(&[
            "xcrun",
            "-sdk",
            "macosx",
            "metal",
            "-fsyntax-only",
            "-x",
            "metal",
        ])
        .arg(input.path())
        .current_dir(util::root().join("kernels"))
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()?;
        let output = child.wait_with_output()?;

        println!(
            "{} {name}",
            if output.status.success() {
                "ok"
            } else {
                "FAIL"
            }
        );

        failed |= !output.status.success();

        print_diagnostics(&String::from_utf8_lossy(&output.stderr));
    }

    let current = fs::read_to_string(util::root().join(CLANGD_PATH)).unwrap_or_default();

    if current == clangd_config() {
        println!("ok {CLANGD_PATH}");
    } else {
        println!("FAIL {CLANGD_PATH} (stale; run `cargo xtask clangd`)");

        failed = true;
    }

    ensure!(!failed, "Metal syntax check failed");

    Ok(())
}

fn print_diagnostics(stderr: &str) {
    let mut seen = HashSet::new();
    let mut keep = true;

    for line in stderr.lines() {
        if line.contains(": error:") || line.contains(": warning:") {
            keep = seen.insert(line);
        }

        if keep {
            eprintln!("{line}");
        }
    }
}

fn smoke(kind: Smoke, model: Option<PathBuf>, binary: Option<PathBuf>) -> Result<()> {
    if binary.is_none() {
        util::build()?;
    }

    let mut command = util::command(&["cargo", "test", "-p", "xtask", "--test", "smoke"]);
    let name = match kind {
        Smoke::All => None,
        Smoke::Server => Some("server_smoke"),
        Smoke::Control => Some("control_smoke"),
        Smoke::Sessions => Some("concurrency::"),
        Smoke::Download => Some("download_smoke"),
    };

    if let Some(name) = name {
        command.arg(name);
    }

    command.args(["--", "--ignored", "--test-threads=1", "--nocapture"]);

    if let Some(model) = model {
        command.env("CHERENKOV_MODEL_DIR", model.canonicalize()?);
    }

    if let Some(binary) = binary {
        command.env("CHERENKOV_BINARY", binary.canonicalize()?);
    }

    ensure!(command.status()?.success(), "smoke tests failed");

    Ok(())
}

fn main() -> Result<()> {
    match Cli::parse().command {
        Task::Bench(options) => {
            xtask::capture::install_interrupt_handler()?;

            bench::run(options)
        }
        Task::Prefill(options) => {
            xtask::capture::install_interrupt_handler()?;

            prefill::run(options)
        }
        Task::Summarize { directory } => {
            let data = util::json(&directory.join("report.json"))?;

            if data.get("prompts").is_some() {
                prefill::write_summary(&directory, &data)
            } else {
                report::regenerate(&directory, &data)
            }
        }
        Task::Readme { directory } => xtask::readme::update(&directory),
        Task::Docs => xtask::docs::build(),
        Task::CheckMetal => check_metal(),
        Task::CheckAuthor { login } => {
            xtask::authors::check(&util::root().join("AUTHORS"), &login)?;

            println!("@{login} is listed in AUTHORS.");

            Ok(())
        }
        Task::Clangd => write_clangd(),
        Task::Smoke {
            kind,
            model,
            binary,
        } => smoke(kind, model, binary),
    }
}
